### PR TITLE
Update Translate

### PR DESCRIPTION
**Pull request by 8MiYile**

### CODE REVIEW

**Comment by LeoColomb** [comment]
Thanks for opening this PR @8MiYile.
This looks really nice, but as it is a plugin, it should go in the correct plugin section.
Could you update accordingly?

**Comment by 8MiYile** [comment]
@LeoColomb 
Hello, it's like this.
This plugin is responsible for language management, as well as discard the original manual download of language packs.
It doesn't matter where he puts it.
But I would like to see it as an advanced language pack plugin.
Because he is mainly to manage the download of language packs and whether to allow the user to load the
In fact, I hope this plugin can be used as the

**Comment by 8MiYile** [comment]
@LeoColomb 
Oh, wait a minute. I found a problem.
https://github.com/YOURLS/YOURLS/issues/3674

**Comment by ozh** [comment]
Yes please, with the plugins

**Comment by 8MiYile** [comment]
@ozh can you reopen this https://github.com/YOURLS/YOURLS/issues/3674
and Related pull requests
Because if you haven't solved the problem over there, my plugin is just a showpiece

**Comment by LeoColomb** [comment]
Closing in favor of https://github.com/YOURLS/YOURLS/issues/3674 discussion.

**Comment by 8MiYile** [comment]
@LeoColomb 
https://github.com/YOURLS/YOURLS/pull/3679
So when does this come through?

**Pull request closed without merging**
